### ISSUE TITLE
[SIDECAR] `execution_result` type mismatch

### ISSUE THREAD

**Issue by ryoknz** [casper-network/casper-sidecar#284]
`execution_result` type is incorrect in the `info_get_deploy` RPC method.
Current type: [`null`](https://github.com/casper-network/casper-sidecar/blob/feat-2.0/resources/test/rpc_schema.json#L306)
Actual type: undefined

https://github.com/casper-network/casper-sidecar/blob/016a0f2c2dbf1f3dab75ac58f8d130035e6a7c97/rpc_sidecar/src/rpcs/info.rs#L130-L131

**Please check all the fields where serialization is skipped especially for `Option<T>`, they should be `undefined` in the schema.**

**Comment by zajko** [comment]
Hi @ryo-casper 
I'm looking at how we handled `info_get_deploy` in 1.x node and how we return it in sidecar for 2.0
Those are two different structures. The old one had a collection of execution results, the new one has one optional. The json schema actually allows all three:
* `"execution_result": <value>`
* `"execution_result": null`
*  no `execution_result` field at all
I'm not sure what the problem here is exactly, please explain. You expect the response value to be exactly the same as the 1.x one?

**Comment by ryoknz** [comment]
Please keep only those cases
> "execution_result": value
"execution_result": null

 and remove this
> no execution_result field at all
